name: test build

on: push

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install curl clang cmake ninja-build pkg-config libgtk-3-dev libblkid-dev liblzma-dev libjsoncpp-dev cmake-data libsecret-1-dev libsecret-1-0 librhash0 libssl-dev -y
      - name: Prepare fluffychat
        run: |
          git clone https://github.com/krille-chan/fluffychat.git -b main
      - uses: ./fluffychat/.github/workflows/release.yaml
