name: test build

on: push

jobs:
  build_linux:
    runs-on: ubuntu-latest
    env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: krille-chan/fluffychat
          path: fluffychat
      - run: |
          #cd fluffychat
          #cat .github/workflows/versions.env >> $GITHUB_ENV
          gh variable list
          release_name=$(gh release view -R krille-chan/fluffychat --json name -q .name)
          gh variable set LAST_FLUFFYCHAT_RELEASE --body "$release_name"
          gh variable list
