name: test build

on: push

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: krille-chan/fluffychat
      - run: |
          ls
