name: test build

on: push

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: krille-chan/fluffychat
          path: fluffychat
      - uses: ./fluffychat/.github/workflows/release.yaml
