name: test build

on: push

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: krille-chan/fluffychat
          path: fluffychat
      - run: |
          #cd fluffychat
          #cat .github/workflows/versions.env >> $GITHUB_ENV
          gh variable list
          gh variable set LAST_FLUFFYCHAT_COMMIT --body "Set from workflow"
          gh variable list
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
