name: build release

on: 
  push:
  schedule:
    # Every tuesday at 10
    - cron: '0 10 * * 2'
  workflow_dispatch:

concurrency:
  group: release_workflow
  cancel-in-progress: true

jobs:
  build_windows:
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install curl clang cmake ninja-build pkg-config libgtk-3-dev libblkid-dev liblzma-dev libjsoncpp-dev cmake-data libsecret-1-dev libsecret-1-0 librhash0 libssl-dev -y
          sudo apt-get install webkit2gtk-4.1
      - name: Prepare fluffychat
        run: |
          git clone https://github.com/krille-chan/fluffychat.git -b main
      - name: import env
        run: |
          cd fluffychat
          cat .github/workflows/versions.env >> $GITHUB_ENV
          
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
          
      - run:  |
          cd fluffychat
          flutter pub get
          flutter build windows --release
          #tar -czf fluffychat-linux-x64.tar.gz -C build/linux/x64/release/bundle/ .
